=== ttlyceo/Lineage-II---Server-Files/Lineage II - Elite H5 Project - Source/ZeuS_Sunrise_Core/dist/game/data/xsd/gabriel/phantom/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" maxOccurs="unbounded">
					<xs:complexType>
                        <xs:sequence>
                            <xs:element name="playerGrade" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="armors" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="ids" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="weapons" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="ids" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="jewels" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="ids" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="others" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="ids" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="grade" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
						<xs:attribute name="classId" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/Lineage-II---Server-Files/Lineage II - Elite H5 Project - Compiled/Beta/game/data/xml/gabriel/phantom/items.xml
<?xml version='1.0' encoding='utf-8'?>
<!--
possible classIds:
See final of file!
Items per class and grade
if more than one house, it will randomly take one
ex:
<armors ids="356,2468,2438,2414"/>
<armors ids="60,64,517,2468"/>
-->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../xsd/gabriel/phantom/items.xsd">

    <item classId="fighter">
		
        <playerGrade grade="no-grade">
            <armors ids="43,2386,23,20,39"/>
            <weapons ids="102,66"/>
            <jewels ids="115,115,877,877,908"/>
            <others ids=""/>
        </playerGrade>
    </item>

    <item classId="warrior">
        <playerGrade grade="D">
            <armors ids="352,2378,2411,2422,2447"/>
            <armors ids="352,2378,2411,2424,2450"/>
            <weapons ids="2499"/>
            <weapons ids="159"/>
	    <weapons ids="225"/>
            <jewels ids="881,881,850,850,913"/>
            <others ids="1463"/>
        </playerGrade>	
    </item>

    <item classId="gladiator">
        <playerGrade grade="C">
            <armors ids="398,418,2455,2431,2414"/> 
	    <armors ids="356,2414,2462,2438"/>
            <weapons ids="8848"/>
            <weapons ids="8837"/>
            <jewels ids="886,886,854,854,119"/>
            <others ids="1464"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2376,2415,5714,5730,2379"/>
            <armors ids="2416,358,2380,5718,5734"/>
            <armors ids="2381,2417,5722,5738"/>
            <armors ids="5710,5726,503,357,383"/>
            <weapons ids="2624"/>
	    <weapons ids="2620"/>
	    <weapons ids="2626"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1465"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2383,2419,5774,5786"/>
	    <armors ids="374,2418,5771,5783"/>
	    <armors ids="2382,574,5768,5780"/>
            <weapons ids="5706"/>
            <weapons ids="5705"/>
            <weapons ids="5704"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1466"/>
        </playerGrade>
    </item>

    <item classId="warlord">
        <playerGrade grade="C">
            <armors ids="398,418,2455,2431,2414"/> 
	    <armors ids="356,2414,2462,2438"/>
            <weapons ids="299"/>
	    <weapons ids="303"/>
   	    <weapons ids="95"/>
            <jewels ids="886,886,854,854,119"/>
            <others ids="1464"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2376,2415,5714,5730"/>
            <armors ids="2416,358,2380,5718,5734"/>
            <armors ids="2381,2417,5722,5738"/>
            <armors ids="5710,5726,503,357,383"/>
            <weapons ids="4859"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1465"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2383,2419,5774,5786"/>
	    <armors ids="374,2418,5771,5783"/>
	    <armors ids="2382,574,5768,5780"/>
            <weapons ids="5633"/>
	    <weapons ids="8803"/>
            <jewels ids="933,871,871,902,902"/>
            <others ids="1466"/>
        </playerGrade>
    </item>

    <item classId="knight">
        <playerGrade grade="D">
            <armors ids="352,2378,2411,2422,2447"/>
            <armors ids="352,2378,2411,2424,2450"/>
            <weapons ids="2499"/>
            <weapons ids="159"/>
	    <weapons ids="225"/>
            <jewels ids="881,881,850,850,913"/>
            <others ids="1463"/>
        </playerGrade>	
    </item>

    <item classId="paladin">
        <playerGrade grade="C">
            <armors ids="398,418,2455,2431,2414"/> 
	    <armors ids="356,2414,2462,2438"/>
            <weapons ids="135"/>
	    <weapons ids="2503"/>
            <jewels ids="886,886,854,854,119"/>
            <others ids="1464"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2376,2415,5714,5730"/>
            <armors ids="2416,358,2380,5718,5734"/>
            <armors ids="2381,2417,5722,5738"/>
            <armors ids="5710,5726,503,357,383"/>
            <weapons ids="79"/>
	    <weapons ids="4753"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1465"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2383,2419,5774,5786"/>
	    <armors ids="374,2418,5771,5783"/>
	    <armors ids="2382,574,5768,5780"/>
            <weapons ids="4720"/>
	    <weapons ids="5602"/>
	    <weapons ids="5648"/>
	    <weapons ids="8135"/>
            <jewels ids="933,871,871,902,902"/>
            <others ids="1466"/>
        </playerGrade>
    </item>

    <item classId="darkAvenger">
        <playerGrade grade="C">
            <armors ids="398,418,2455,2431,2414"/> 
	    <armors ids="356,2414,2462,2438"/>
            <weapons ids="135"/>
	    <weapons ids="2503"/>
            <jewels ids="886,886,854,854,119"/>
            <others ids="1464"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2376,2415,5714,5730"/>
            <armors ids="2416,358,2380,5718,5734"/>
            <armors ids="2381,2417,5722,5738"/>
            <armors ids="5710,5726,503,357,383"/>
            <weapons ids="79"/>
	    <weapons ids="4753"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1465"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2383,2419,5774,5786"/>
	    <armors ids="374,2418,5771,5783"/>
	    <armors ids="2382,574,5768,5780"/>
            <weapons ids="4720"/>
	    <weapons ids="5602"/>
	    <weapons ids="5648"/>
	    <weapons ids="8135"/>
            <jewels ids="933,871,871,902,902"/>
            <others ids="1466"/>
        </playerGrade>
    </item>

    <item classId="rogue">
        <playerGrade grade="D">
            <armors ids="352,2378,2411,2424,2450"/>
            <weapons ids="225"/>
	    <weapons ids="1660"/>
            <jewels ids="881,881,850,850,913"/>
            <others ids="1463"/>
        </playerGrade>
    </item>

    <item classId="treasureHunter">
        <playerGrade grade="C">
            <armors ids="398,418,2455,2431,2414"/> 
	    <armors ids="397,2387,608,62,2414"/> 
	    <armors ids="401,2461,2437,2414"/> 
            <weapons ids="228"/> 
	    <weapons ids="233"/>
            <jewels ids="886,886,854,854,119"/> 
            <others ids="1464"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2417,2392,5723,5739"/>
	    <armors ids="2391,2416,5719,5735"/>
            <weapons ids="229"/>
	    <weapons ids="234"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1465"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2395,5775,2419,5787"/>
	    <armors ids="10798,5784,5772,3418"/>
	    <armors ids="2385,2389,512,5766,5778"/> 
            <weapons ids="8801"/> 
	    <weapons ids="5618"/> 
	    <weapons ids="4783"/>
            <jewels ids="933,871,871,902,902"/>
            <others ids="1466"/>
        </playerGrade>
    </item>

    <item classId="hawkeye">
        <playerGrade grade="C">
            <armors ids="398,418,2455,2431,2414"/> 
	    <armors ids="397,2387,608,62,2414"/> 
	    <armors ids="401,2461,2437,2414"/> 
            <weapons ids="286"/>
            <jewels ids="886,886,854,854,119"/> 
            <others ids="1464"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2417,2392,5723,5739"/>
	    <armors ids="2391,2416,5719,5735"/>
            <weapons ids="4829"/>
	    <weapons ids="286"/>
            <jewels ids="895,895,864,864,926"/>
            <others ids="1465,1464"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2395,5775,2419,5787"/>
	    <armors ids="10798,5784,5772,3418"/>
	    <armors ids="2385,2389,512,5766,5778"/> 
            <weapons ids="5612"/> 
            <weapons ids="8807"/>
            <jewels ids="933,871,871,902,902"/>
            <others ids="1466"/>
        </playerGrade>
    </item>

    <item classId="mage">
        <playerGrade grade="no-grade">
            <armors ids="44,1104,1101,39,51,102"/>
            <weapons ids="310"/>
            <jewels ids="115,115,877,877,908"/>
            <others ids=""/>
        </playerGrade>
    </item>

    <item classId="wizard">
        <playerGrade grade="D">
            <armors ids="44,1104,1101,39,51,102"/>
            <weapons ids="189"/> 
	    <weapons ids="190"/> 
	    <weapons ids="188"/>
            <jewels ids="881,881,850,850,913"/>
            <others ids="3948"/>
        </playerGrade>
    </item>

    <item classId="sorceror">
        <playerGrade grade="C">
            <armors ids="439,471,2459,2430,2414"/>
	    <armors ids="442,473,2463,603,2414"/>
	    <armors ids="441,472,2459,2435,2414"/>
            <weapons ids="84"/>
	    <weapons ids="203"/>
   	    <weapons ids="206"/> 
	    <weapons ids="205"/> 
            <jewels ids="886,886,854,854,119"/>
            <others ids="3949"/>
        </playerGrade>
        <playerGrade grade="B">
            <armors ids="2406,5716,5732,2415"/>
	    <armors ids="2398,2403,5720,5736,2416"/>
            <weapons ids="7722,673"/>
	    <weapons ids="8141,673"/>
            <jewels ids="895,895,864,864,926"/> 
            <others ids="3950"/>
        </playerGrade>
        <playerGrade grade="A">
            <armors ids="2409,5776,5788,2419"/>
	    <armors ids="2408,5773,5785,2418"/>
	    <armors ids="512,2407,5767,5779"/>
            <weapons ids="5643,641"/>
	    <weapons ids="5643,641"/> 
	    <weapons ids="8150,2498"/> 
	    <weapons ids="8149,2498"/>
            <jewels ids="933,871,871,902,902"/>
            <others ids="3951"/>
        </playerGrade>
    </item>

    <item classId="necromancer">
        <playerGrade grade="C">
            <armors ids="439,471,2459,2430,2414"/>
	    <armors ids="442,473,2463,603,2414"/>
	    <armors ids="441,472,2459,2435,2414"/>
