=== ttlyceo/Lineage-II---Server-Files/Lineage II - Elite H5 Project - Compiled/Beta/game/data/xsd/gabriel/dailyLogin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DailyLogin" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
                            <xs:element name="Day" minOccurs="28" maxOccurs="28">
                                <xs:complexType>
                                    <xs:attribute name="day" type="xs:string"></xs:attribute>
                                    <xs:attribute name="itemid" type="xs:int"></xs:attribute>
                                    <xs:attribute name="count" type="xs:int"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
						</xs:sequence>
						<xs:attribute name="MonthNumber" type="xs:int"></xs:attribute>
						<xs:attribute name="MonthName" type="xs:string"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/Lineage-II---Server-Files/Lineage II - Elite H5 Project - Compiled/Live/game/data/xml/gabriel/dailyLoginPremium.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- 
/**
 * @author Gabriel Costa Souza
 * Discord: Gabriel 'GCS'#2589
 * Skype - email: gabriel_costa25@hotmail.com
 */

-->
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/gabriel/dailyLogin.xsd">
    <DailyLogin MonthNumber="1" MonthName="January">
        <Day day="day01" itemid="20034" count="10"/>
        <Day day="day02" itemid="20336" count="1"/>
        <Day day="day03" itemid="49002" count="30"/>
        <Day day="day04" itemid="13518" count="1"/>
        <Day day="day05" itemid="17074" count="3"/>
        <Day day="day06" itemid="17071" count="1"/>
        <Day day="day07" itemid="21585" count="1"/>
        <Day day="day08" itemid="20034" count="20"/>
        <Day day="day09" itemid="20338" count="1"/>
        <Day day="day10" itemid="49002" count="50"/>
        <Day day="day11" itemid="6578" count="5"/>
        <Day day="day12" itemid="6577" count="5"/>
        <Day day="day13" itemid="10514" count="1"/>
        <Day day="day14" itemid="14947" count="1"/>
        <Day day="day15" itemid="20034" count="30"/>
        <Day day="day16" itemid="20340" count="1"/>
        <Day day="day17" itemid="49002" count="100"/>
        <Day day="day18" itemid="13015" count="1"/>
        <Day day="day19" itemid="20033" count="3"/>
        <Day day="day20" itemid="13016" count="5"/>
        <Day day="day21" itemid="48011" count="1"/>
        <Day day="day22" itemid="47008" count="1"/>
        <Day day="day23" itemid="47033" count="1"/>
        <Day day="day24" itemid="47039" count="1"/>
        <Day day="day25" itemid="47027" count="1"/>
        <Day day="day26" itemid="47021" count="1"/>
        <Day day="day27" itemid="21707" count="10"/>
        <Day day="day28" itemid="21706" count="1"/>
    </DailyLogin>
    <DailyLogin MonthNumber="2" MonthName="February">
        <Day day="day01" itemid="57" count="1"/>
        <Day day="day02" itemid="57" count="1"/>
        <Day day="day03" itemid="57" count="1"/>
        <Day day="day04" itemid="57" count="1"/>
        <Day day="day05" itemid="57" count="1"/>
        <Day day="day06" itemid="57" count="1"/>
        <Day day="day07" itemid="57" count="1"/>
        <Day day="day08" itemid="57" count="1"/>
        <Day day="day09" itemid="57" count="1"/>
        <Day day="day10" itemid="57" count="10"/>
        <Day day="day11" itemid="57" count="10"/>
        <Day day="day12" itemid="57" count="10"/>
        <Day day="day13" itemid="57" count="10"/>
        <Day day="day14" itemid="57" count="10"/>
        <Day day="day15" itemid="57" count="10"/>
        <Day day="day16" itemid="57" count="10"/>
        <Day day="day17" itemid="57" count="10"/>
        <Day day="day18" itemid="57" count="10"/>
        <Day day="day19" itemid="57" count="10"/>
        <Day day="day20" itemid="57" count="20"/>
        <Day day="day21" itemid="57" count="20"/>
        <Day day="day22" itemid="57" count="20"/>
        <Day day="day23" itemid="57" count="20"/>
        <Day day="day24" itemid="57" count="20"/>
        <Day day="day25" itemid="57" count="20"/>
        <Day day="day26" itemid="57" count="20"/>
        <Day day="day27" itemid="57" count="20"/>
        <Day day="day28" itemid="57" count="20"/>
    </DailyLogin>
    <DailyLogin MonthNumber="3" MonthName="March">
        <Day day="day01" itemid="57" count="1"/>
        <Day day="day02" itemid="57" count="1"/>
        <Day day="day03" itemid="57" count="1"/>
        <Day day="day04" itemid="57" count="1"/>
        <Day day="day05" itemid="57" count="1"/>
        <Day day="day06" itemid="57" count="1"/>
        <Day day="day07" itemid="57" count="1"/>
        <Day day="day08" itemid="57" count="1"/>
        <Day day="day09" itemid="57" count="1"/>
        <Day day="day10" itemid="57" count="10"/>
        <Day day="day11" itemid="57" count="10"/>
        <Day day="day12" itemid="57" count="10"/>
        <Day day="day13" itemid="57" count="10"/>
        <Day day="day14" itemid="57" count="10"/>
        <Day day="day15" itemid="57" count="10"/>
        <Day day="day16" itemid="57" count="10"/>
        <Day day="day17" itemid="57" count="10"/>
        <Day day="day18" itemid="57" count="10"/>
        <Day day="day19" itemid="57" count="10"/>
        <Day day="day20" itemid="57" count="20"/>
        <Day day="day21" itemid="57" count="20"/>
        <Day day="day22" itemid="57" count="20"/>
        <Day day="day23" itemid="57" count="20"/>
        <Day day="day24" itemid="57" count="20"/>
        <Day day="day25" itemid="57" count="20"/>
        <Day day="day26" itemid="57" count="20"/>
        <Day day="day27" itemid="57" count="20"/>
        <Day day="day28" itemid="57" count="20"/>
    </DailyLogin>
    <DailyLogin MonthNumber="4" MonthName="April">
        <Day day="day01" itemid="57" count="1"/>
        <Day day="day02" itemid="57" count="1"/>
        <Day day="day03" itemid="57" count="1"/>
        <Day day="day04" itemid="57" count="1"/>
        <Day day="day05" itemid="57" count="1"/>
        <Day day="day06" itemid="57" count="1"/>
        <Day day="day07" itemid="57" count="1"/>
        <Day day="day08" itemid="57" count="1"/>
        <Day day="day09" itemid="57" count="1"/>
        <Day day="day10" itemid="57" count="10"/>
        <Day day="day11" itemid="57" count="10"/>
        <Day day="day12" itemid="57" count="10"/>
        <Day day="day13" itemid="57" count="10"/>
        <Day day="day14" itemid="57" count="10"/>
        <Day day="day15" itemid="57" count="10"/>
        <Day day="day16" itemid="57" count="10"/>
        <Day day="day17" itemid="57" count="10"/>
        <Day day="day18" itemid="57" count="10"/>
        <Day day="day19" itemid="57" count="10"/>
        <Day day="day20" itemid="57" count="20"/>
        <Day day="day21" itemid="57" count="20"/>
        <Day day="day22" itemid="57" count="20"/>
        <Day day="day23" itemid="57" count="20"/>
        <Day day="day24" itemid="57" count="20"/>
        <Day day="day25" itemid="57" count="20"/>
        <Day day="day26" itemid="57" count="20"/>
        <Day day="day27" itemid="57" count="20"/>
        <Day day="day28" itemid="57" count="20"/>
    </DailyLogin>
    <DailyLogin MonthNumber="5" MonthName="May">
        <Day day="day01" itemid="57" count="1"/>
        <Day day="day02" itemid="57" count="1"/>
        <Day day="day03" itemid="57" count="1"/>
        <Day day="day04" itemid="57" count="1"/>
        <Day day="day05" itemid="57" count="1"/>
        <Day day="day06" itemid="57" count="1"/>
        <Day day="day07" itemid="57" count="1"/>
        <Day day="day08" itemid="57" count="1"/>
        <Day day="day09" itemid="57" count="1"/>
        <Day day="day10" itemid="57" count="10"/>
        <Day day="day11" itemid="57" count="10"/>
        <Day day="day12" itemid="57" count="10"/>
        <Day day="day13" itemid="57" count="10"/>
        <Day day="day14" itemid="57" count="10"/>
        <Day day="day15" itemid="57" count="10"/>
        <Day day="day16" itemid="57" count="10"/>
        <Day day="day17" itemid="57" count="10"/>
        <Day day="day18" itemid="57" count="10"/>
        <Day day="day19" itemid="57" count="10"/>
        <Day day="day20" itemid="57" count="20"/>
        <Day day="day21" itemid="57" count="20"/>
        <Day day="day22" itemid="57" count="20"/>
        <Day day="day23" itemid="57" count="20"/>
        <Day day="day24" itemid="57" count="20"/>
        <Day day="day25" itemid="57" count="20"/>
        <Day day="day26" itemid="57" count="20"/>
        <Day day="day27" itemid="57" count="20"/>
        <Day day="day28" itemid="57" count="20"/>
    </DailyLogin>
    <DailyLogin MonthNumber="6" MonthName="June">
        <Day day="day01" itemid="57" count="1"/>
        <Day day="day02" itemid="57" count="1"/>
        <Day day="day03" itemid="57" count="1"/>
        <Day day="day04" itemid="57" count="1"/>
        <Day day="day05" itemid="57" count="1"/>
        <Day day="day06" itemid="57" count="1"/>
        <Day day="day07" itemid="57" count="1"/>
        <Day day="day08" itemid="57" count="1"/>
        <Day day="day09" itemid="57" count="1"/>
        <Day day="day10" itemid="57" count="10"/>
        <Day day="day11" itemid="57" count="10"/>
        <Day day="day12" itemid="57" count="10"/>
        <Day day="day13" itemid="57" count="10"/>
        <Day day="day14" itemid="57" count="10"/>
        <Day day="day15" itemid="57" count="10"/>
        <Day day="day16" itemid="57" count="10"/>
        <Day day="day17" itemid="57" count="10"/>
        <Day day="day18" itemid="57" count="10"/>
        <Day day="day19" itemid="57" count="10"/>
        <Day day="day20" itemid="57" count="20"/>
        <Day day="day21" itemid="57" count="20"/>
        <Day day="day22" itemid="57" count="20"/>
        <Day day="day23" itemid="57" count="20"/>
        <Day day="day24" itemid="57" count="20"/>
        <Day day="day25" itemid="57" count="20"/>
        <Day day="day26" itemid="57" count="20"/>
        <Day day="day27" itemid="57" count="20"/>
        <Day day="day28" itemid="57" count="20"/>
    </DailyLogin>
    <DailyLogin MonthNumber="7" MonthName="July">
        <Day day="day01" itemid="57" count="1"/>
        <Day day="day02" itemid="57" count="1"/>
        <Day day="day03" itemid="57" count="1"/>
        <Day day="day04" itemid="57" count="1"/>
        <Day day="day05" itemid="57" count="1"/>
        <Day day="day06" itemid="57" count="1"/>
        <Day day="day07" itemid="57" count="1"/>
        <Day day="day08" itemid="57" count="1"/>
        <Day day="day09" itemid="57" count="1"/>
        <Day day="day10" itemid="57" count="10"/>
        <Day day="day11" itemid="57" count="10"/>
        <Day day="day12" itemid="57" count="10"/>
        <Day day="day13" itemid="57" count="10"/>
        <Day day="day14" itemid="57" count="10"/>
        <Day day="day15" itemid="57" count="10"/>
        <Day day="day16" itemid="57" count="10"/>
